# Generated by Django 4.1.3 on 2022-11-07 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Days',
            new_name='Day',
        ),
    ]
